### ISSUE TITLE
Any ideas about app-store safety?

### ISSUE THREAD

**Issue by zats** [ekurutepe/MPNotificationView#10]
Hi and thank you for sharing this great component!
As far as I understand it's the best way to mimic messages and email behaviour 
Did you try yourself or know anyone who successfully submitted an app to the app store with this component?
Thanks!

**Comment by ekurutepe** [comment]
[Moped](http://www.moped.com) has an update including this control under review right now. I'll update the main page when the review process is finished.

**Comment by ekurutepe** [comment]
[Our update](http://appstore.com/moped) containing this control was released a few weeks ago with no problems. This component shouldn't pose a review problem.

**Comment by zats** [comment]
Thanks, Engin!
