### ISSUE TITLE
Incorrect orientation

### ISSUE THREAD

**Issue by palringosteve** [ekurutepe/MPNotificationView#12]
If the app is started in landscape mode with the home button to the left, the notification view appears vertically on the right side of the screen. It seems to think the device is still in the default portrait mode.

Rotating the device to portrait and back to landscape (regardless of whether or not a notification is showing) causing subsequent notifications to appear in the correct place and orientation (horizontally along the top of the screen).

**Comment by ekurutepe** [comment]
closed by #18
