### ISSUE TITLE
MPNotificationView:383  semantic issue

### ISSUE THREAD

**Issue by mumumuu** [ekurutepe/MPNotificationView#19]
![Screen Shot 2013-03-19 at 4 57 38 PM](https://f.cloud.github.com/assets/3908284/275058/7bfcbfa0-907b-11e2-880b-204ccec87697.png)

Works if replaced with
"viewToRotateIn = [__notificationWindow.notificationQueue objectAtIndex:0];"

**Comment by ekurutepe** [comment]
Please build against the latest SDK. The brackets notation is introduced starting iOS6 SDK and can be deployed down to iOS4.3

**Comment by mumumuu** [comment]
Weird, I build against the latest SDK and use modern Objective-C everywhere in the project. More than that - method "objectAtIndexedSubscript" is visible. Still has this error after reboot/deleting derived data even in sample project. Most probably this is just local Xcode issue. Sorry for disturbing and thank you for your time.

**Comment by ekurutepe** [comment]
What is your deployment target? Could be related to that if it's below 4.3.

**Comment by mumumuu** [comment]
iOS 5.1
