### ISSUE TITLE
Never run in delegate method

### ISSUE THREAD

**Issue by mjspawn** [ekurutepe/MPNotificationView#29]
in MPNotificationView.m

at handleTap()

if (_tapBlock != nil)
    {
        _tapBlock(self);
    }

```
if ([_delegate respondsToSelector:@selector(tapReceivedForNotificationView:)])
{
    [_delegate didTapOnNotificationView:self];
}

[[NSNotificationCenter defaultCenter] postNotificationName:kMPNotificationViewTapReceivedNotification
                                                    object:self];
```

change to

if (_tapBlock != nil)
    {
        _tapBlock(self);
    } else if ([_delegate respondsToSelector:@selector(didTapOnNotificationView:)])
    {
        [_delegate didTapOnNotificationView:self];
    } else
    {
        [[NSNotificationCenter defaultCenter] postNotificationName:kMPNotificationViewTapReceivedNotification
                                                            object:self];
    }

**Comment by benkax** [comment]
yes, same problem here,  if ([_delegate respondsToSelector:@selector(tapReceivedForNotificationView:)]) will never be true, any fix already?

**Comment by mjspawn** [comment]
why always post notification?

**Comment by ekurutepe** [comment]
Why not?
